spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/fis_police
    username: sa
    password:
    driver-class-name: org.h2.Driver
# 작성자: 고준영, 작성내용: mailjet이 안먹어서, 다시 mailplug로 시도 해봤는데, "mail.stmp.ssl.enable": true 박으니까 갑자기 잘 됨 ㅋㅋ 개꿀;
  mail:
    host:
    port: 465
    username: fis182@fisolution.co.kr
    password: fis1234*
    properties:
      "mail.smtp.ssl.enable": true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# 작성자 이승범, 작성내용: naver map api secret key 숨기기위해 yml파일 새로파서 include
  profiles:
    include:
      - map

  jpa:
    hibernate:
      ddl-auto: create-drop  # 작성자 이승범 ddl-auto: create-drop 해놓음
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.Type: trace



