spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/fis_police
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # 작성자: 원보라, 작성내용: swagger 라이브러리 오류 방지
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 작성자: 고준영, 작성내용: mialjet, mailplug 사용할 수 있고, mailplug 선택함
  mail:
    host: smtp.mailplug.co.kr
    port: 465
    username: fis182@fisolution.co.kr
    password: fis1234*
    properties:
      "mail.smtp.ssl.enable": true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #          ssl:
  #            enable: true
  # 작성자 이승범, 작성내용: naver map api secret key 숨기기위해 yml파일 새로파서 include
  profiles:
    include:
      - map

  jpa:
    hibernate:
      ddl-auto: create  # 작성자 이승범 ddl-auto: create-drop 해놓음
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.Type: trace


