spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/fis_police
    username: bora
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.Type: trace
    org.apache.coyote.http11: debug

naver:
  client:
    id: vb8g27znp3
    secret: z5APZIFSWO5KyiQjE3QDleGDsGVBdz4IGkYpFQT5
