
name: CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: asddsa
        run: pwd
        shell: bash
      
      - name: qweewq
        run: ls -l
        shell: bash
      
      - name: move to fisDir
        run: cd ./fis_police_server
        shell: bash
        
      - name: aq
        run: ls -l
        shell: bash

      - name: sw
        run: cd ./fis_police_server
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        
